### ISSUE TITLE
FileNotFoundError: Could not find any ONNX model file for the regex

### ISSUE THREAD

**Issue by garyritchie** [breezedeus/Pix2Text#112]
Ubuntu 22.04.4 LTS with python 3.10

If I do 

```bash
p2t predict -l en,ch_sim --file-type text_formula -i image/ch1mathtype1-26.jpg
```

I get

```bash
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/gary/.local/lib/python3.10/site-packages/pix2text/doc_xl_layout/../../exp/ctdet_subfield/default
heads {'hm': 11, 'cls': 4, 'ftype': 3, 'wh': 8, 'hm_sub': 2, 'wh_sub': 8, 'reg': 2, 'reg_sub': 2}
[INFO 2024-05-22 16:27:37,500 load_model:36] loading model from local file: /home/gary/.pix2text/1.1/layout-parser/DocXLayout_231012.pth 
[INFO 2024-05-22 16:27:37,518 _get_model:194] use model: /home/gary/.cnocr/2.3/densenet_lite_136-gru/cnocr-v2.3-densenet_lite_136-gru-epoch=004-ft-model.onnx 
[INFO 2024-05-22 16:27:37,544 _assert_and_prepare_model_files:135] use model: /home/gary/.cnstd/1.2/ppocr/ch_PP-OCRv3_det_infer.onnx 
[INFO 2024-05-22 16:27:37,585 select_device:104] YOLOv7 🚀 2024-5-20 torch 2.3.0+cu121 CPU
 
[INFO 2024-05-22 16:27:37,585 __init__:168] Use model: /home/gary/.cnstd/1.2/analysis/mfd-yolov7_tiny.pt 
[INFO 2024-05-22 16:27:37,680 __init__:597]  
[INFO 2024-05-22 16:27:37,783 __init__:83] Use model dir for LatexOCR: /home/gary/.pix2text/1.1/mfr-onnx 
Traceback (most recent call last):
  File "/home/gary/.local/bin/p2t", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/gary/.local/lib/python3.10/site-packages/pix2text/cli.py", line 178, in predict
    p2t = Pix2Text.from_config(
  File "/home/gary/.local/lib/python3.10/site-packages/pix2text/pix_to_text.py", line 101, in from_config
    text_formula_ocr = TextFormulaOCR.from_config(
  File "/home/gary/.local/lib/python3.10/site-packages/pix2text/text_formula_ocr.py", line 135, in from_config
    latex_ocr = LatexOCR(**formula_config)
  File "/home/gary/.local/lib/python3.10/site-packages/pix2text/latex_ocr.py", line 93, in __init__
    self.model, self.processor = self._init_model(
  File "/home/gary/.local/lib/python3.10/site-packages/pix2text/latex_ocr.py", line 143, in _init_model
    model = ORTModelForVision2Seq.from_pretrained(
  File "/home/gary/.local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 669, in from_pretrained
    return super().from_pretrained(
  File "/home/gary/.local/lib/python3.10/site-packages/optimum/modeling_base.py", line 402, in from_pretrained
    return from_pretrained_method(
  File "/home/gary/.local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_seq2seq.py", line 836, in _from_pretrained
    decoder_without_past_path = ORTModelForConditionalGeneration.infer_onnx_filename(
  File "/home/gary/.local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 435, in infer_onnx_filename
    raise FileNotFoundError(f"Could not find any ONNX model file for the regex {patterns} in {path}.")
FileNotFoundError: Could not find any ONNX model file for the regex ['(.*)?decoder((?!(with_past|merged)).)*?\\.onnx'] in /home/gary/.pix2text/1.1/mfr-onnx.
```

**Comment by breezedeus** [comment]
There should be missing files in the `/home/gary/.pix2text/1.1/mfr-onnx` directory, you can delete this folder and let it re-download automatically.

**Comment by garyritchie** [comment]
That works, thank you!
