### ISSUE TITLE
1.1.2使用报错

### ISSUE THREAD

**Issue by xuanyucode** [breezedeus/Pix2Text#158]
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/doclayout_yolo/assets/releases/tags/v8.1.0 (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))

**Comment by xuanyucode** [comment]
手动下载模型到pix2text\1.1\layout-docyolo文件夹下，识别又会报错：max() arg is an empty sequence

**Comment by breezedeus** [comment]
发下完整的报错信息

**Comment by xuanyucode** [comment]
> 发下完整的报错信息
拉取新的1.1.2库之后报错信息：
: FutureWarning: Ignoring --local-dir-use-symlinks. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
Traceback (most recent call last):
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000022B2EA925E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/breezedeus/pix2text-layout-docyolo/revision/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022B2EA925E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 155, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\hf_api.py", line 2756, in repo_info
    return method(
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\hf_api.py", line 2540, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/breezedeus/pix2text-layout-docyolo/revision/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022B2EA925E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"), '(Request ID: 965578cb-b0ac-46ce-a4d7-8e37e77a3ad3)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Software\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Software\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Project\pythonStudy\ocr\.venv\Scripts\huggingface-cli.exe\__main__.py", line 7, in <module>
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\commands\huggingface_cli.py", line 57, in main
    service.run()
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\commands\download.py", line 153, in run
    print(self._download())  # Print path to downloaded files
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\commands\download.py", line 187, in _download
    return snapshot_download(
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Project\pythonStudy\ocr\.venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 235, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
'HF_ENDPOINT' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
⚠️ GitHub assets check failure for https://api.github.com/repos/doclayout_yolo/assets/releases/tags/v8.1.0: 404 Not Found
⚠️ GitHub assets check failure for https://api.github.com/repos/doclayout_yolo/assets/releases/latest: 404 Not Found
2024-11-26_08:36:08 - ！！！承包合同识别出错：[Errno 2] No such file or directory: 'C:\\Users\\26896\\AppData\\Roaming\\pix2text\\1.1\\layout-docyolo\\doclayout_yolo_docstructbench_imgsz1024.pt'
手动下载依赖后：
![image](https://github.com/user-attachments/assets/a3217da4-154f-4104-9aef-6663da182615)

![image](https://github.com/user-attachments/assets/e5f59247-dee2-46e6-a0a2-2e9beb906327)

**Comment by xuanyucode** [comment]
我感觉应该是python3.8的问题，3.8的pandas最高到2.0.3版本，这些数组和dataframe的报错应该是低版本pandas导致的吧。。可是3.9以上打包之后，又不支持在win7上运行，我现在卡住了。。

**Comment by breezedeus** [comment]
前面的问题是下载模型的问题，你已经修复了。后面的问题把报错信息都输出下啊😅
