### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by mayurankv** [breezedeus/Pix2Text#22]
I get the following error running `pip3 install pix2text`:

```
Collecting onnx (from cnocr>=2.2.2.2->pix2text)
  Using cached onnx-1.11.0.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... done
  Using cached onnx-1.10.2.tar.gz (9.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached onnx-1.10.1.tar.gz (10.0 MB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of onnxruntime to determine which version is compatible with other requirements. This could take a while.
  Using cached onnx-1.10.0.tar.gz (10.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kw/0h0s01y50yjbplk5qxt3s4n40000gn/T/pip-install-vo4i04b2/onnx_9f89c413a2ea40d88a4ea00bf24d0e70/setup.py", line 318, in <module>
          raise FileNotFoundError("Unable to find " + requirements_file)
      FileNotFoundError: Unable to find requirements.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Skipping /usr/local/lib/python3.11/site-packages/SciPy-1.10.1-py3.11.egg-info due to invalid metadata entry 'name'
```

I'm not sure how to fix it?

**Comment by breezedeus** [comment]
use Python 3.8 ~ 3.10, don't use 3.11.

**Comment by mayurankv** [comment]
Ah, thank you
