### ISSUE TITLE
BUG:     pix2text\utils.py    IndexError: string index out of range

### ISSUE THREAD

**Issue by huanggefan** [breezedeus/Pix2Text#46]
```python
Traceback (most recent call last):
  File "Z:\open_huanggefan\AIKnowledgePlatform\AIKnowledgePlatform\aigc\utils\pdf_extract.py", line 74, in <module>
    only_text = merge_line_texts(outs, auto_line_break=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SDK\python3.11.4\venv\Lib\site-packages\pix2text\utils.py", line 436, in merge_line_texts
    line_text_list = [smart_join(o) for o in out_texts]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SDK\python3.11.4\venv\Lib\site-packages\pix2text\utils.py", line 436, in <listcomp>
    line_text_list = [smart_join(o) for o in out_texts]
                      ^^^^^^^^^^^^^
  File "C:\SDK\python3.11.4\venv\Lib\site-packages\pix2text\utils.py", line 398, in smart_join
    if (is_chinese(res[-1]) and is_chinese(str_list[i][0])) or contain_whitespace(res[-1] + str_list[i][0]):
                                                                                            ~~~~~~~~~~~^^^
IndexError: string index out of range
```

before `pix2text\utils.py:400`, shoule check `len(str_list[i])`

```python
        if len(str_list[i]) < 1:
            continue
        if (is_chinese(res[-1]) and is_chinese(str_list[i][0])) or contain_whitespace(
            res[-1] + str_list[i][0]
        ):
            res += str_list[i]
        else:
            res += ' ' + str_list[i]
````

**Comment by breezedeus** [comment]
V0.3 已修复，感谢～
