### ISSUE TITLE
BUG:ValueError: Asked to use CUDAExecutionProvider as an ONNX Runtime execution provider, but the available execution providers are ['AzureExecutionProvider', 'CPUExecutionProvider'].

### ISSUE THREAD

**Issue by Hongru0306** [breezedeus/Pix2Text#65]
您好，当我在使用脚本进行推理的时候，出现了以下的报错,用的是您官方readme里面的脚本:
```
from pix2text import Pix2Text, merge_line_texts

img_fp = './docs/examples/en1.jpg'
p2t = Pix2Text()
outs = p2t.recognize(img_fp, resized_shape=608)  # 也可以使用 `p2t(img_fp)` 获得相同的结果
print(outs)
# 如果只需要识别出的文字和Latex表示，可以使用下面行的代码合并所有结果
only_text = merge_line_texts(outs, auto_line_break=True)
print(only_text)
```
出现下面的报错:
```
Traceback (most recent call last):
  File "/CV/xhr_project/Paper_all/OcrData/Pix2Text/tools/pred.py", line 4, in <module>
    p2t = Pix2Text()
  File "/CV/anaconda3/envs/data_process/lib/python3.9/site-packages/pix2text/pix_to_text.py", line 78, in __init__
    self.latex_model = LatexOCR(**formula_config)
  File "/CV/anaconda3/envs/data_process/lib/python3.9/site-packages/pix2text/latex_ocr.py", line 85, in __init__
    self.model, self.processor = self._init_model(
  File "/CV/anaconda3/envs/data_process/lib/python3.9/site-packages/pix2text/latex_ocr.py", line 141, in _init_model
    model.to(self.device)
  File "/CV/anaconda3/envs/data_process/lib/python3.9/site-packages/optimum/onnxruntime/modeling_seq2seq.py", line 1103, in to
    validate_provider_availability(provider)  # raise error if the provider is not available
  File "/CV/anaconda3/envs/data_process/lib/python3.9/site-packages/optimum/onnxruntime/utils.py", line 271, in validate_provider_availability
    raise ValueError(
ValueError: Asked to use CUDAExecutionProvider as an ONNX Runtime execution provider, but the available execution providers are ['AzureExecutionProvider', 'CPUExecutionProvider'].
```
求助！！这个问题困扰了我好久。

**Comment by Hongru0306** [comment]
补充，环境是按照您repo里面的进行`pip install -r requirments.txt`,具体如下:
```
Package                  Version
------------------------ -----------
aiohttp                  3.9.3
aiosignal                1.3.1
appdirs                  1.4.4
asttokens                2.4.1
async-timeout            4.0.3
attrs                    23.2.0
backcall                 0.2.0
certifi                  2024.2.2
charset-normalizer       3.3.2
click                    8.1.7
cnocr                    2.3.0.1
cnstd                    1.2.3.5
coloredlogs              15.0.1
comm                     0.2.1
contourpy                1.2.0
cycler                   0.12.1
datasets                 2.17.0
debugpy                  1.6.7
decorator                5.1.1
dill                     0.3.8
docker-pycreds           0.4.0
easyocr                  1.7.1
entrypoints              0.4
evaluate                 0.4.1
executing                2.0.1
filelock                 3.13.1
flatbuffers              23.5.26
fonttools                4.49.0
frozenlist               1.4.1
fsspec                   2023.10.0
gitdb                    4.0.11
GitPython                3.1.42
huggingface-hub          0.20.3
humanfriendly            10.0
idna                     3.6
imageio                  2.34.0
importlib-resources      6.1.1
ipykernel                6.29.3
ipython                  8.12.0
jedi                     0.19.1
Jinja2                   3.1.3
jupyter-client           7.3.4
jupyter_core             5.7.1
kiwisolver               1.4.5
lazy_loader              0.3
lightning-utilities      0.10.1
MarkupSafe               2.1.5
matplotlib               3.8.3
matplotlib-inline        0.1.6
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
nest_asyncio             1.6.0
networkx                 3.2.1
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
onnx                     1.15.0
onnxruntime              1.17.0
opencv-python            4.9.0.80
opencv-python-headless   4.9.0.80
optimum                  1.16.2
packaging                23.2
pandas                   2.2.0
parso                    0.8.3
pexpect                  4.9.0
pickleshare              0.7.5
pillow                   10.2.0
pip                      23.3.1
pix2text                 1.0
platformdirs             4.2.0
Polygon3                 3.0.9.1
prompt-toolkit           3.0.42
protobuf                 4.25.3
psutil                   5.9.8
ptyprocess               0.7.0
pure-eval                0.2.2
pyarrow                  15.0.0
pyarrow-hotfix           0.6
pyclipper                1.3.0.post5
Pygments                 2.17.2
pyparsing                3.1.1
python-bidi              0.4.2
python-dateutil          2.8.2
pytorch-lightning        2.2.0.post0
pytz                     2024.1
PyYAML                   6.0.1
pyzmq                    25.1.2
regex                    2023.12.25
requests                 2.31.0
responses                0.18.0
safetensors              0.4.2
scikit-image             0.22.0
scipy                    1.12.0
seaborn                  0.13.2
sentencepiece            0.1.99
sentry-sdk               1.40.4
setproctitle             1.3.3
setuptools               68.2.2
shapely                  2.0.2
six                      1.16.0
smmap                    5.0.1
stack-data               0.6.2
sympy                    1.12
tifffile                 2024.2.12
tokenizers               0.15.2
torch                    2.2.0
torchmetrics             1.3.1
torchvision              0.17.0
tornado                  6.1
tqdm                     4.66.2
traitlets                5.14.1
transformers             4.37.2
triton                   2.2.0
typing_extensions        4.9.0
tzdata                   2024.1
Unidecode                1.3.8
urllib3                  2.2.0
wandb                    0.16.3
wcwidth                  0.2.13
wheel                    0.41.2
xxhash                   3.4.1
yarl                     1.9.4
zipp                     3.17.0
```
python=3.9

**Comment by breezedeus** [comment]
你是在GPU 机器上跑么？如果想用 GPU，记得卸载 onnxruntime，装 onnxruntime-gpu ，可以参考这个说明：https://ldib281k94.feishu.cn/docx/C4uDdTuHao58ruxnnGKcqIF5nnf#WyAYdADJjoXaSNxM7jzcai8Xnmg

**Comment by MSZ-006NOC** [comment]
您好，我同样也遇到了这个问题，我在完全删除onnxruntime后，安装了onnxruntime-gpu版本，同时测试CUDAExecutionProvider能够正常获取。
然后我在使用脚本进行推理的时候遇到了如下问题
`ValueError: When using CUDAExecutionProvider, the parameters combination use_cache=False, use_io_binding=True is not supported. Please either pass use_cache=True, use_io_binding=True (default), or use_cache=False, use_io_binding=False.`
问题出现在
```
Traceback (most recent call last):
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fymr/Python_Project/tphone/service_pic_to_text.py", line 11, in image_reco
    p2t = Pix2Text()
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/pix2text/pix_to_text.py", line 78, in __init__
    self.latex_model = LatexOCR(**formula_config)
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/pix2text/latex_ocr.py", line 85, in __init__
    self.model, self.processor = self._init_model(
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/pix2text/latex_ocr.py", line 138, in _init_model
    model = ORTModelForVision2Seq.from_pretrained(
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 662, in from_pretrained
    return super().from_pretrained(
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/optimum/modeling_base.py", line 399, in from_pretrained
    return from_pretrained_method(
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/optimum/onnxruntime/modeling_seq2seq.py", line 1006, in _from_pretrained
    return cls(
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/optimum/onnxruntime/modeling_seq2seq.py", line 1873, in __init__
    super().__init__(
  File "/home/fymr/ENTER/envs/tora/lib/python3.10/site-packages/optimum/onnxruntime/modeling_seq2seq.py", line 674, in __init__
    raise ValueError(

```
希望得到您的解答，感谢！！！

**Comment by breezedeus** [comment]
收到，我去复现下

**Comment by breezedeus** [comment]
@MSZ-006NOC 发布了新版 v1.0.1 修复此问题，感谢。 https://github.com/breezedeus/Pix2Text/releases
